version: '3.8'

services:
  db:
    container_name: ${PROJECT_NAME}_database
    image: postgres:14
    restart: always
    volumes:
      - ${PROJECT_NAME}_database_data:/var/lib/postgresql/data
    ports:
      - ${HOST_POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: ../
      dockerfile: deploy/backend.Dockerfile
    restart: always
    ports:
      - ${HOST_BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db

volumes:
 transactions_database_data: